server:
  port: 8082

spring:
  application:
    name: analytics-service

  # database
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: adquiz
    password: adquiz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.adquiz.*"
        spring.json.type.mapping: >
          com.adquiz.content.kafka.AnswerSubmittedEvent:com.adquiz.analytics.kafka.AnswerSubmittedEvent,
          com.adquiz.content.kafka.SessionCompletedEvent:com.adquiz.analytics.kafka.SessionCompletedEvent

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/adquiz

# Actuator:
management:
  endpoints:
    web:
      exposure:
        include: health, info
