import { useTheme } from '../../context/ThemeContext'
import { login, register } from '../../auth/AuthProvider'
import './LandingPage.css'

export default function LandingPage() {
  const { isDark, toggleTheme } = useTheme()

  return (
    <div className="landing">
    <div className="landing-blob blob-1"></div>
    <div className="landing-blob blob-2"></div>
    <div className="landing-blob blob-3"></div>

    <header className="landing-header">
        <span className="landing-brand">AdQuiz</span>
        <div className="landing-header-right">
          <button className="theme-toggle" onClick={toggleTheme}>
            {isDark ? '☀' : '☾'}
          </button>
          <button className="btn-secondary btn-sm" onClick={() => login()}>
            Login
          </button>
        </div>
      </header>

      <section className="hero">
        <div className="hero-content">
          <h1 className="hero-title">
            Learn smarter with <span className="highlight">adaptive quizzes</span>
          </h1>
          <p className="hero-subtitle">
            AI-generated questions that adapt to your level.
            Spaced repetition that knows when you need to review.
            Track your progress and master any topic.
          </p>
          <div className="hero-actions">
            <button className="btn-primary" onClick={() => register()}>
              Get started — it's free
            </button>
            <button className="btn-secondary" onClick={() => login()}>
              I already have an account
            </button>
          </div>
        </div>
        <div className="hero-mockup">
          <div className="mockup-window">
            <div className="mockup-titlebar">
              <span className="mockup-dot red"></span>
              <span className="mockup-dot yellow"></span>
              <span className="mockup-dot green"></span>
            </div>
            <div className="mockup-body">
              <div className="mockup-sidebar">
                <div className="mockup-nav-item active"></div>
                <div className="mockup-nav-item"></div>
                <div className="mockup-nav-item"></div>
                <div className="mockup-nav-item"></div>
              </div>
              <div className="mockup-main">
                <div className="mockup-greeting"></div>
                <div className="mockup-stats">
                  <div className="mockup-stat purple"></div>
                  <div className="mockup-stat"></div>
                  <div className="mockup-stat"></div>
                </div>
                <div className="mockup-card">
                  <div className="mockup-card-line w60"></div>
                  <div className="mockup-card-line w40"></div>
                </div>
                <div className="mockup-card">
                  <div className="mockup-card-line w80"></div>
                  <div className="mockup-progress-bar">
                    <div className="mockup-progress-fill"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="features">
        <h2 className="section-title">Everything you need to learn effectively</h2>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">🧠</div>
            <h3 className="feature-name">AI-powered questions</h3>
            <p className="feature-desc">
              Questions generated by AI across 6 Bloom's Taxonomy levels,
              from basic recall to advanced evaluation.
            </p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📅</div>
            <h3 className="feature-name">Spaced repetition</h3>
            <p className="feature-desc">
              The SM-2 algorithm schedules reviews at the optimal time,
              so you review right before you forget.
            </p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📊</div>
            <h3 className="feature-name">Progress tracking</h3>
            <p className="feature-desc">
              See your accuracy per topic, identify weak areas,
              and track daily activity with a visual heatmap.
            </p>
          </div>
        </div>
      </section>

      <section className="how-it-works">
        <h2 className="section-title">How it works</h2>
        <div className="steps">
          <div className="step">
            <div className="step-number">1</div>
            <h3 className="step-name">Pick a topic</h3>
            <p className="step-desc">
              Search for any topic. AdQuiz generates fresh questions
              tailored to your chosen subject.
            </p>
          </div>
          <div className="step-connector"></div>
          <div className="step">
            <div className="step-number">2</div>
            <h3 className="step-name">Answer adaptive questions</h3>
            <p className="step-desc">
              Questions get harder as you improve. Rate your confidence
              so the algorithm understands your true level.
            </p>
          </div>
          <div className="step-connector"></div>
          <div className="step">
            <div className="step-number">3</div>
            <h3 className="step-name">Review at the right time</h3>
            <p className="step-desc">
              Spaced repetition tells you exactly when to review.
              Build long-term memory, not short-term cramming.
            </p>
          </div>
        </div>
      </section>

      <section className="stats-section">
        <div className="stats-grid">
          <div className="stat-item">
            <div className="stat-value">6</div>
            <div className="stat-label">Bloom's Taxonomy levels</div>
          </div>
          <div className="stat-item">
            <div className="stat-value">SM-2</div>
            <div className="stat-label">Spaced repetition algorithm</div>
          </div>
          <div className="stat-item">
            <div className="stat-value">∞</div>
            <div className="stat-label">AI-generated questions</div>
          </div>
          <div className="stat-item">
            <div className="stat-value">100%</div>
            <div className="stat-label">Personalized to you</div>
          </div>
        </div>
      </section>

      <section className="cta-section">
        <h2 className="cta-title">Ready to learn smarter?</h2>
        <p className="cta-subtitle">
          Start your first adaptive quiz in under a minute.
        </p>
        <button className="btn-primary btn-lg" onClick={() => register()}>
          Get started — it's free
        </button>
      </section>

      <footer className="landing-footer">
        <span className="landing-brand footer-brand">AdQuiz</span>
        <p>Built with AI-powered question generation and SM-2 spaced repetition</p>
      </footer>
    </div>
  )
}