package com.adquiz.aigeneration.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GeneratedQuestionDto {

    // The question text generated by AI
    private String questionText;

    // Answer options - display only, no correct flag
    private List<OptionDto> options;

    // The correct option ID - server-side only, never sent to frontend
    private String correctAnswer;

    // Explanation shown to student after answering
    private String explanation;

    // Bloom's taxonomy's level of this question - echoed backk from request
    private int bloomLevel;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class OptionDto {
        // Option identifier — "a", "b", "c", "d"
        private String id;

        // Option display text
        private String text;
    }
}
